name: Build from push

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/build-hugo-site
        with:
          base-url: "https://playbooks.hyperblazer.net"
      - uses: dwhswenson/static-site-workflow/actions/store-artifacts@main
        with:
          site-dir: "_site"
