name: Cleanup staging
description: Cleanup staging environment; this occurs on PR merge or close

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: dwhswenson/static-site-workflow/actions/cleanup-staging@main
        with:
          aws-region: us-east-2
          aws-role: ${{ secrets.STAGING_ROLE }}
          bucket-name: ${{ secrets.STAGING_BUCKET }}

      - uses: dwhswenson/static-site-workflow/actions/update-staging-index@main
        with:
          aws-region: us-east-2
          aws-role: ${{ secrets.STAGING_ROLE }}
          bucket-name: ${{ secrets.STAGING_BUCKET }}
          website-url: ${{ vars.STAGING_WEBSITE }}
