name: Cleanup staging
description: Cleanup staging environment; this occurs on PR merge or close

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Delete Cloudflare Preview Deployment
        run: |
          BRANCH_NAME="pr${PR_NUMBER}"
          echo "Deleting all deployments for branch: $BRANCH_NAME"

          DEPLOYMENTS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/YOUR_PROJECT_NAME/deployments" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json")

          DEPLOYMENT_IDS=$(echo "$DEPLOYMENTS" | jq -r --arg branch "$BRANCH_NAME" '.result[] | select(.deployment_trigger.metadata.branch == $branch) | .id')

          if [ -z "$DEPLOYMENT_IDS" ]; then
            echo "No deployments found for branch: $BRANCH_NAME"
          else
            echo "Deleting the following deployments:"
            echo "$DEPLOYMENT_IDS"
            
            for ID in $DEPLOYMENT_IDS; do
              echo "Deleting Deployment ID: $ID"
              curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/YOUR_PROJECT_NAME/deployments/$ID" \
                -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                -H "Content-Type: application/json"
            done
          fi
