name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install s3cmd
        run: |
          python -m pip install s3cmd
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
      - name: Build
        run: hugo --minify
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_PRODUCTION_ROLE }}
      - name: Deploy
        run: |
          s3cmd sync --delete-removed public/ s3://${{ secrets.AWS_S3_BUCKET }}
          # fix up a problem with the content type of css files
          aws s3 cp public/css/*.css s3://${{ secrets.AWS_S3_BUCKET }}/css/ --content-type "text/css"

