name: Nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    strategy:
      matrix:
        hugo-version:
          - '0.141.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: omsf-eco-infra/static-site-tools/build/hugo@main
        with:
          hugo-version: ${{ matrix.hugo-version }}
