name: Deploy to production

on:
  workflow_run:
    workflows: ["Build from push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-from-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: omsf-eco-infra/static-site-tools/.github/workflows/prod-cloudflare.yaml@main
    with:
      run_id: ${{ github.event.workflow_run.id }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

