name: Upload to staging

on:
  workflow_run:
    workflows: ["Build from PR"]
    types:
      - completed

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ env.PR_NUM }}
      pr_headsha: ${{ env.PR_HEADSHA }}

    # TODO: move this to a separate action
    steps:
      - name: Get PR number and head SHA
        run: |
          PR_NUM=$(jq -r '.workflow_run.pull_requests[0].number' "$GITHUB_EVENT_PATH")
          HEAD_SHA=$(jq -r '.workflow_run.head_commit.id' "$GITHUB_EVENT_PATH")

          echo "PR_NUM=$PR_NUM" | tee -a $GITHUB_ENV
          echo "PR_HEADSHA=$HEAD_SHA" | tee -a $GITHUB_ENV

  stage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: get-metadata
    uses: ./.github/workflows/inner-stage-cloudflare.yaml
    with:
      run-id: ${{ github.event.workflow_run.id }}
      pr-number: ${{ fromJSON(needs.get-metadata.outputs.pr_number) }}  # convert to int
      pr-headsha: ${{ needs.get-metadata.outputs.pr_headsha }}
      project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
