name: Staging comment

on:
  workflow_run:
    workflows: ["Upload to staging"]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Get metadata
        uses: dwhswenson/static-site-workflow/actions/get-metadata@main
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Post comment with metadata
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ env.PR_NUM }}
          message: |
            This PR has been staged at ${{ vars.STAGING_WEBSITE }}/${{ env.PR_NUM }}/.

            Updated for commit ${{ env.PR_HEADSHA }}.

