name: Upload to GoStatic

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ./.github/actions/build-hugo-site
        with:
          base-url: ""

      - name: Upload to GoStatic
        id: gostatic
        uses: DigitalSVN/GoStatic@v1.0
        with:
          api-token: ${{ secrets.GOSTATIC_API_TOKEN }}
          source-dir: _site

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gostatic
          number: ${{ github.event.pull_request.number }}
          message: |
            This PR has been staged at ${{ steps.gostatic.outputs.url }}.
            
            Updated for commit ${{ github.event.pull_request.head.sha }}.


